version: 2
updates:
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  reviewers:
  - jbhannah
  ignore:
  - dependency-name: github.com/prometheus/common
    versions:
    - 0.15.0
    - 0.16.0
    - 0.17.0
    - 0.18.0
    - 0.19.0
    - 0.20.0
    - 0.21.0
  - dependency-name: go.mongodb.org/mongo-driver
    versions:
    - 1.4.5
    - 1.4.6
    - 1.5.0
